### ISSUE TITLE
sendMessageUpdates

### ISSUE THREAD

**Issue by Quu1337** [aronson/discord-irc#55]
sendMessageUpdates is only kinda working.

on first edit, it sends the original message again and doesnt show the edited message. on second edit it sends the first edit, but not the second one

![image](https://github.com/aronson/discord-irc/assets/48761355/5216213d-1b4e-45b9-bbe3-b3da07490d39)

**Comment by aronson** [comment]
Resolved in [this release](https://github.com/aronson/discord-irc/releases/tag/6.0.1).

Discord actually sends the original message and *then* the updated message on message updates. I had to figure out which was the right one.

**Comment by Quu1337** [comment]
nice ty, updated and is working properly
