### ISSUE TITLE
Image uploads

### ISSUE THREAD

**Issue by Quu1337** [aronson/discord-irc#56]
Image uploads have different (old style?) nick format

![image](https://github.com/aronson/discord-irc/assets/48761355/d582788e-fc74-4811-8966-9608dd80f28c)

image with text-attached

**Comment by aronson** [comment]
Did you configure the `urlAttachment` property? It's working on my end as expected.

```json
  "format": {
    "commandPrelude": "{$nickname} said:",
    "ircText": "<{$displayUsername} [@{$discordUsername}]> {$text}",
    "urlAttachment": "<{$displayUsername} [@{$discordUsername}]> {$attachmentURL}",
    "discord": "<@**{$author}**> {$withMentions}"
  },
```

**Comment by aronson** [comment]
Default behavior and README have been updated to reflect the desired behavior
